let urunler = [
    {
      isim: "FIFA23",
      açıklama: "FIFA23",
      fiyat: 19.99,
      fotoğraf: "./images/fifa23.jpg",
      stok: 150,
    },
    {
      isim: "NBA2K22",
      açıklama: "NBA2K22",
      fiyat: 29.99,
      fotoğraf: "./images/nba.jpg",
      stok: 100,
    },
    {
      isim: "GTA5",
      açıklama: "GTA5",
      fiyat: 39.99,
      fotoğraf: "./images/gta.webp",
      stok: 75,
    },
    {
        isim: "FM24",
        açıklama: "FM24",
        fiyat: 59.99,
        fotoğraf: "./images/fm.jpg",
        stok: 75,
      },
    {
      isim: "FAR CRY6",
      açıklama: "FAR CRY6",
      fiyat: 11.99,
      fotoğraf: "./images/farcry6.png",
      stok: 120,
    },
    {
        isim: "FORZA HORİZON 5",
        açıklama: "FORZA HORİZON 5",
        fiyat: 16.39,
        fotoğraf: "./images/forzahorizon5.jpg",
        stok: 120,
      },
      {
        isim: "ETS 2",
        açıklama: "ETS 2",
        fiyat: 2.52,
        fotoğraf: "./images/ets2.jpg",
        stok: 120,
      },
      {
        isim: "RDR 2",
        açıklama: "RDR 2",
        fiyat: 19.79,
        fotoğraf: "./images/rdr2.jpeg",
        stok: 120,
      },
      {
        isim: "CYBERPUNK 2077",
        açıklama: "CYBERPUNK 2077",
        fiyat: 22.49,
        fotoğraf: "./images/cyberpunk.jpeg",
        stok: 120,
      },
      {
        isim: "RUST",
        açıklama: "RUST",
        fiyat: 26.79,
        fotoğraf: "./images/rust.webp",
        stok: 120,
      },
      {
        isim: "BATTLEFIELD 4",
        açıklama: "BATTLEFIELD 4",
        fiyat: 9.59,
        fotoğraf: "./images/battlefield.jpeg",
        stok: 120,
      },
      {
        isim: "DARK SOULS",
        açıklama: "DARK SOULS",
        fiyat: 19.99,
        fotoğraf: "./images/darksouls.jpeg",
        stok: 120,
      },
  ];
  